### ISSUE TITLE
BE: プロフィールのSNS情報が未登録の場合

### ISSUE THREAD

**Issue by neutron0831** [optim22team/optim_22_app#39]
現状では
`sns: null`
となっているが
`sns: {
    github: "",
    twitter: "",
    facebook: ""
}`
が望ましい

**Comment by nibuiro** [comment]
#40 にて対応しました。
よろしくお願いします。

**Comment by neutron0831** [comment]
ブランチissue#40で正しく新規登録されていることを確認しました！
ご対応ありがとうございました🙇‍♂️
