### ISSUE TITLE
BE: ユーザ情報がデータベースに新規登録されない

### ISSUE THREAD

**Issue by neutron0831** [optim22team/optim_22_app#40]
ユーザ登録リクエスト時にステータス200が返されるが、レスポンスのAuthorizationヘッダに含まれるアクセストークンをデコードして得られるユーザIDを元にプロフィール取得リクエストを行っても、`user_id: 0`の空のプロフィールが返って来てしまう。

例えば、ユーザが5人登録されている状態で新規登録を行うとステータス200と共にアクセストークンを返してユーザID6が返されるため、おそらく何らかの形で新規登録は行われているようだが、その後マイページにリダイレクトしプロフィール情報を取得するために
`GET /api/user/6`
のリクエストを送信しても、ユーザID6のユーザプロフィールではなくユーザID0の空のプロフィールが応答されてしまう。

**Comment by nibuiro** [comment]
プロフィール未登録状態が未定義なので現在そのようになってます。<_ _>

**Comment by nibuiro** [comment]
ブランチissue#40にて対応しました。

**Comment by nibuiro** [comment]
mergeしました。
ご確認ありがとうございました。🙇‍♂️
