### ISSUE TITLE
BE: ディスカッションにコメントが投稿できない

### ISSUE THREAD

**Issue by neutron0831** [optim22team/optim_22_app#49]
`400: Bad Request`が応答され、コメントが投稿できない

**Comment by nibuiro** [comment]
通ってしまいます...
![image](https://user-images.githubusercontent.com/31338759/136952545-d52938eb-874a-4161-85ad-0f457aca2cf1.png)

**Comment by nibuiro** [comment]
現在のmainブランチで問題の再現はこちらで可能ですか？
ちなみに現在全許可なのでアクセストークンの問題は起きないはずです。

**Comment by nibuiro** [comment]
お待ちを、すべてというのは？

**Comment by neutron0831** [comment]
了解です。
どの機能が整数でどの機能が文字列かが分かればこちらで対応できるので、大丈夫です！
上記の分担で、フロントエンドで対応します。
