### ISSUE TITLE
BE: POSTやPUTメソッドに関してユーザ認証がなされていない

### ISSUE THREAD

**Issue by neutron0831** [optim22team/optim_22_app#56]
アクセストークンによるユーザ認証が必要なPOSTやPUTメソッドのHTTPリクエストに関して、ユーザ認証が行われていないようである。
そのため、現時点ではログインユーザでなくともプロフィール/リクエスト/サブミッションの書き換えなどができてしまっている。

**Comment by neutron0831** [comment]
了解しました！
ただ、ユーザが恣意的に書き換えたアクセストークンが、有効期限内の他のユーザのアクセストークンと一致する確率が非常に低いため、現在の実装で問題ない(ほぼ“ユーザ本人でなくとも”とみなしていい)と思います！

**Comment by nibuiro** [comment]
issue#56 ブランチにて有効化しましたのでpostmanにてForbiddenが返されることと、問題なくフロントエンドの操作が通ることのご確認をよろしくお願いします。

**Comment by neutron0831** [comment]
Postmanとブラウザで正しくForbiddenされることを確認しました！
ただ、新規ユーザ登録をしようとした際にも`403 Forbidden`が返されてしまうようです

**Comment by neutron0831** [comment]
そうです、usernameが編集できませんでした。
了解です！
アクセストークンが無効なPUT/POSTに対してはForbiddenされていていることを確認したので、mergeしていただいて大丈夫です！

**Comment by nibuiro** [comment]
マージしました🚀🚀
