### ISSUE TITLE
BE: ディスカッションのコメント投稿者の名前とアイコンが正しくない

### ISSUE THREAD

**Issue by neutron0831** [optim22team/optim_22_app#58]
- ディスカッションのコメント一覧取得APIの応答に含まれる投稿者の名前が`username: ""`となっている。
- コメントの投稿者のアイコンがbase64形式でない(`icon: "ZGF0YTppbW...VDWUlJPQ=="`となっている)。
また、この文字列`"ZGF0YTppbW...VDWUlJPQ=="`はissue#38
#38
の文字列と一致していることから、この問題がissue#38と関連している可能性が高い

**Comment by nibuiro** [comment]
#52にて対応しました。
