### ISSUE TITLE
受け取るbodyサイズに上限が存在しない脆弱性

### ISSUE THREAD

**Issue by ishimomo** [optim22team/optim_22_app#70]
受け取るbodyサイズをバッファで制限していれば落ちることはないのか検証
>  Webサーバがbodyを制限なく受け入れるとbodyサイズだけサーバのメモリが消費されるため、
>  大きなbodyを送信しサーバをダウンさせるセキュリティホールになります。
>  そのため、API側で受け取れるbodyに上限を設けることは、Webに公開するAPIの場合必須になります。
>  
>  その点は注意したうえで実装してください。
[GinでBodyを取得する際の最大サイズについて - Qiita](https://qiita.com/daemonkimura/items/9462f68c4bb5afa439de)

**Comment by nibuiro** [comment]
```
Y:\>curl -i -X PUT -H "Content-Type:application/json" -d @E:\mnt\attack2.bin http://localhost:8080/api/user/11
HTTP/1.1 400 Bad Request
Date: Mon, 18 Oct 2021 05:14:35 GMT
Content-Length: 0
```
fsutilコマンドにて8GBのゼロ埋めファイルを作成しcurlにてPOSTする実験の結果メモリを8GB消費することなく400エラーが返ってきた。Windowsのメモリ圧縮の効果なのか、釈然としない。調査の限りginはデフォルトでリクエストサイズに上限を設けていない。APIサーバプログラムにて明示的に上限付きバッファを確保することが望ましいとも思われるが、リバースプロキシを設けその段階でサイズ上限を設けた方が人為ミスの発生率も減りプログラミングコストも多少下がる。

**Comment by nibuiro** [comment]
ネットワーク通信量の確認の結果ファイルサイズが大きすぎてcurlが正常に動作していないと思われる。

**Comment by nibuiro** [comment]
https://github.com/json-iterator/test-data/blob/master/large-file.json
このファイルは25MBほどであり、この状態を送信すると400が返ってくる。
しかし、goroutineを落とすために増幅したものは通信量を監視する限り送信に失敗している。
curlの問題。
```
#bash
cat large-file.json > large-file2.json
for i in 0 1 2 3 4 5 6 7 8 9
do
cat large-file.json >> large-file2.json
done
```
